const dogs = [
  {
    name: "Max",
    avatar: "images/dogs/akita.webp",
    age: "11",
    bio: "Adventurous spirit, ready to explore.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "images/dogs/airedale-terrier.webp",
    age: "10",
    bio: "Tail-wagging ball of fluff and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Charlie",
    avatar: "images/dogs/alaskan-Husky.webp",
    age: "12",
    bio: "Snow-loving Husky seeking adventure partner.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Milo",
    avatar: "images/dogs/alaskan-malamute.webp",
    age: "12",
    bio: "Powerful grace, gentle soul within.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Oliver",
    avatar: "images/dogs/american-Foxhound.webp",
    age: "11",
    bio: "Chasing scents with a wag!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Buddy",
    avatar: "images/dogs/american-staffordshire.webp",
    age: "10",
    bio: "Loving heart, loyal and playful.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Coco",
    avatar: "images/dogs/aussie-bulldog.webp",
    age: "12",
    bio: "Spirited cuddler with Aussie charm.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rocky",
    avatar: "images/dogs/australian-Cobberdog.webp",
    age: "13",
    bio: "Gentle soul, spreading love and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Oscar",
    avatar: "images/dogs/bichon-frise.webp",
    age: "12",
    bio: "Fluffy bundle, spreading smiles daily.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sadie",
    avatar: "images/dogs/border-terrier.webp",
    age: "12",
    bio: "Feisty adventurer, heart full of loyalty.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Jack",
    avatar: "images/dogs/cairn-terrier.webp",
    age: "14",
    bio: "Spirited explorer, boundless charm unleashed.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Joe",
    avatar: "images/dogs/cavalier-king-charles-spaniel.webp",
    age: "11",
    bio: "Regal cuddler, spreading love and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Leo",
    avatar: "images/dogs/cavoodle.webp",
    age: "13",
    bio: "I'm the cutest doodle in town!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Molly",
    avatar: "images/dogs/havanese.webp",
    age: "10",
    bio: "Cheerful companion, wagging tail guaranteed.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Duke",
    avatar: "images/dogs/hungarian-vizsla.webp",
    age: "12",
    bio: "Energetic explorer, loyal and loving.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Penny",
    avatar: "images/dogs/irish-setter.webp",
    age: "10",
    bio: "Vibrant spirit, radiating love and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Finn",
    avatar: "images/dogs/maltese-shih-tzu.webp",
    age: "12",
    bio: "Tiny fluffball, big heart inside.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Archie",
    avatar: "images/dogs/miniature-dachshund.webp",
    age: "12",
    bio: "Little wiener, full of big love.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Poppy",
    avatar: "images/dogs/miniature-poodle.webp",
    age: "14",
    bio: "Graceful, intelligent, and endlessly affectionate.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bailey",
    avatar: "images/dogs/miniature-schnauzer.webp",
    age: "13",
    bio: "Spirited companion, full of charm",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Moodle",
    avatar: "images/dogs/moodle.webp",
    age: "14",
    bio: "Cute and cuddly, love tooodle!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Scout",
    avatar: "images/dogs/newfoundland.webp",
    age: "10",
    bio: "Gentle giant, heart as big.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Maxie",
    avatar: "images/dogs/old-english-sheepdog.webp",
    age: "10",
    bio: "Furry clown, spreading joy and laughter.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Chip",
    avatar: "images/dogs/papillon.webp",
    age: "12",
    bio: "Butterfly ears, heart full of joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Toby",
    avatar: "images/dogs/pekingese.webp",
    age: "13",
    bio: "Regal charm in a small package.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Benny",
    avatar: "images/dogs/pomeranian.webp",
    age: "12",
    bio: "Fluffy ball of joy, always smiling.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rocky",
    avatar: "images/dogs/puli.webp",
    age: "12",
    bio: "Lively dreadlocked companion, full of personality",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];
