const dogs = [
  {
    name: "Max",
    avatar: "images/dogs/akita.webp",
    alt: "Cream white Akita dog sitting with its tongue sticking out.",
    age: "11",
    bio: "Adventurous spirit, ready to explore.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Bella",
    avatar: "images/dogs/airedale-terrier.webp",
    alt: "Fluffy brown and black Airedale Terrier dog sitting with its fur.",
    age: "10",
    bio: "Tail-wagging ball of fluff and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Charlie",
    avatar: "images/dogs/alaskan-Husky.webp",
    alt: "Attentive Alaskan Husky sitting, with a sleek white and greyish coat.",
    age: "12",
    bio: "Snow-loving Husky seeking adventure partner.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },

  {
    name: "Coco",
    avatar: "images/dogs/aussie-bulldog.webp",
    alt: "Sitting Aussie Bulldog with a brown and white coat.",
    age: "12",
    bio: "Spirited cuddler with Aussie charm.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rocky",
    avatar: "images/dogs/australian-Cobberdog.webp",
    alt: "Sitting Australian Cobberdog offering a handshake, with a furry brown coat.",
    age: "13",
    bio: "Gentle soul, spreading love and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Oscar",
    avatar: "images/dogs/bichon-frise.webp",
    alt: "Fluffy Bichon Frise standing with its tongue sticking out.",
    age: "12",
    bio: "Fluffy bundle, spreading smiles daily.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Joe",
    avatar: "images/dogs/cavalier-king-charles-spaniel.webp",
    alt: "Sitting Cavalier King Charles Spaniel with a slightly tilted neck, long ears, closed mouth, fluffy white and brown coat.",
    age: "11",
    bio: "Regal cuddler, spreading love and joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Molly",
    avatar: "images/dogs/havanese.webp",
    alt: "Fluffy Havanese dog sitting with a small open mouth, cream, light black, and a touch of light orange coat colors.",
    age: "10",
    bio: "Cheerful companion, wagging tail guaranteed.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },

  {
    name: "Archie",
    avatar: "images/dogs/miniature-dachshund.webp",
    alt: "Miniature Dachshund dog sitting with a band around its neck, ears bent forward.",
    age: "12",
    bio: "Little wiener, full of big love.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Moodle",
    avatar: "images/dogs/moodle.webp",
    alt: "White Moodle dog sitting with an open mouth, fluffy coat resembling sheep's wool.",
    age: "14",
    bio: "Cute and cuddly, love tooodle!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Maxie",
    avatar: "images/dogs/old-english-sheepdog.webp",
    alt: "Sitting Old English Sheepdog with a fluffy white and black coat, and hair covering its eyes.",
    age: "10",
    bio: "Furry clown, spreading joy and laughter.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Chip",
    avatar: "images/dogs/papillon.webp",
    alt: "Papillon dog with butterfly ears, white and brown coat, open mouth, looking towards the left side.",
    age: "12",
    bio: "Butterfly ears, heart full of joy.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Toby",
    avatar: "images/dogs/pekingese.webp",
    alt: "Small fluffy Pekingese dog standing, with a brown coat, a hint of black around the mouth, and ears bent downwards, looking forward.",
    age: "13",
    bio: "Regal charm in a small package.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Benny",
    avatar: "images/dogs/pomeranian.webp",
    alt: "Small Pomeranian dog resembling a cat, with a light brown coat, open mouth, and a slightly tilted neck towards the right side.",
    age: "12",
    bio: "Fluffy ball of joy, always smiling.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rocky",
    avatar: "images/dogs/puli.webp",
    alt: "Puli dog with long curly hair, hair covering eyes, tongue out, and neck slightly bent towards the right side.",
    age: "12",
    bio: "Lively dreadlocked companion, full of personality",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];

export default dogs;
